services:
  app:
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN:-}
      - OWNER_TELEGRAM_ID=${OWNER_TELEGRAM_ID:-}
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=fatbot
      - DB_USER=fatbot
      - DB_PASSWORD=fatbot
    depends_on:
      - mysql
    volumes:
      - ./:/app
    command: python fatbot.py

  mysql:
    ports:
      - 3306:3306
    image: library/mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fatbot
      - MYSQL_USER=fatbot
      - MYSQL_PASSWORD=fatbot
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    volumes:
      # Mount source code for development
      - ./:/app
  mysqltest:
    ports:
      - 3307:3306
    image: library/mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fatbot
      - MYSQL_USER=fatbot
      - MYSQL_PASSWORD=fatbot
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      # Mount source code for development
      - ./:/app
