name: Fatbot CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: fatbot
          MYSQL_USER: fatbot
          MYSQL_PASSWORD: fatbot
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install Pipenv
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
    - name: Cache Pipenv virtualenv
      uses: actions/cache@v3
      id: pipenv-cache
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-
    - name: Install dependencies
      run: |
        pipenv --python 3.10 && pipenv --rm && pipenv install --deploy --dev
      if: steps.pipenv-cache.outputs.cache-hit != 'true'
    - name: Run tests
      run: |
        pipenv run alembic upgrade head
        pipenv run pytest
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOYMENT_SERVER_HOST }}
        username: ${{ secrets.DEPLOYMENT_SERVER_USERNAME }}
        key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
        script: |
          cd /home/yakninja/fatbot
          git pull
          source .venv/bin/activate
          pipenv install --deploy
          pipenv run alembic upgrade head
          sudo $(which systemctl) restart fatbot
